export const IMAGE_URL_PREFIX = "https://raw.githubusercontent.com/Mach131/serpexceed/master/";

export const KNOWN_NAME_MAP = new Map([
    ['doremy_lbol', 'Doremy Sweet (Touhou: Lost Branch of Legend [Joke])'],
    ['funbro', 'Solidad\'s Slowbro (Pokemon [Joke])'],
    ['kebako', 'Kebako (Cat Girl Without Salad [Joke])'],
    ['maple_black_mage', 'Black Mage (Maplestory [Joke])'],
    ['redhood_squigly', 'Silent Redhood & Squigly (Maiden & Spell + Skullgirls [Joke])'],
    ['rouxls', 'Rouxls Kaard (Deltarune [Joke])'],
    ['scary_orange', 'Scary Orange (Annoying Orange [Joke])'],
    ['siivagunner', 'SiIvagunner (Youtube [Joke])'],
    ['spiegelmann', 'Spiegelmann (Maplestory [Joke])'],
    ['sun_ex', 'Sun Priestess EX (Maiden & Spell [Joke])'],
    ['tic_tac_turmoil', 'That Girl (Tic-Tac-Turmoil [Joke])'],
    ['tlsc', 'The Legendary Super Citrus (Annoying Orange [Joke])'],
    ['arcanist', 'Royal Arcanist (Maiden & Spell)'],
    ['depths', 'Depth\'s Secret (Maiden & Spell)'],
    ['frost', 'Hero of Frost (Maiden & Spell)'],
    ['lich', 'Lich of Flowers (Maiden & Spell)'],
    ['redhood', 'Silent Redhood (Maiden & Spell)'],
    ['storm', 'Stormbeast (Maiden & Spell)'],
    ['sunny', 'Sun Priestess (Maiden & Spell)'],
    ['wyrm', 'Dreadwyrm Heir (Maiden & Spell)'],
    ['inkling', 'Inkling / Agent 3 (Splatoon)'],
    ['octoling', 'Octoling / Agent 8 (Splatoon)'],
    ['off_the_hook', 'Off the Hook (Splatoon)'],
    ['squid_sisters', 'Squid Sisters (Splatoon)'],
    ['absa', 'Absa (Rivals of Aether)'],
    ['orcane', 'Orcane (Rivals of Aether)'],
    ['zetterburn', 'Zetterburn (Rivals of Aether)'],
    ['coo', 'Coo (Drapline)'],
    ['jevil', 'Jevil (Deltarune)'],
    ['kumoko', 'Kumoko (So I\'m a Spider, So What?)'],
    ['mami_old', 'Futatsuiwa Mamizou (Touhou [rework needed])'],
    ['miia', 'Miia (Monster Musume)'],
    ['narmaya', 'Narmaya (Granblue Fantasy)'],
    ['papi', 'Papi (Monster Musume)'],
    ['rimuru', 'Rimuru Tempest (That Time I Reincarnated as a Slime)'],
    ['junko', 'Junko (Touhou)'],
    ['kokoro', 'Hata no Kokoro (Touhou)'],
    ['lily', 'Lily White (Touhou)'],
    ['marisa', 'Kirisame Marisa (Touhou)'],
    ['ran', 'Yakumo Ran (Touhou)'],
    ['seija', 'Kijin Seija (Touhou)'],
    ['suika', 'Ibuki Suika (Touhou)'],
    ['suwako', 'Moriya Suwako (Touhou)'],
    ['consul_n', 'Consul N (Xenoblade Chronicles 3)'],
    ['mio', 'Mio (Xenoblade Chronicles 3)'],
    ['noah', 'Noah (Xenoblade Chronicles 3)'],
    ['angelic_buster', 'Angelic Buster (Maplestory)'],
    ['battle_mage', 'Battle Mage (Maplestory)'],
    ['beast_tamer', 'Beast Tamer (Maplestory)'],
    ['bishop', 'Bishop (Maplestory)'],
    ['bowmaster', 'Bowmaster (Maplestory)'],
    ['buccaneer', 'Buccaneer (Maplestory)'],
    ['cadena', 'Cadena (Maplestory)'],
    ['dawn_warrior', 'Dawn Warrior (Maplestory)'],
    ['demon_avenger', 'Demon Avenger (Maplestory)'],
    ['demon_slayer', 'Demon Slayer (Maplestory)'],
    ['evan', 'Evan (Maplestory)'],
    ['fire_poison', 'Archmage of Fire/Poison (Maplestory)'],
    ['hero', 'Hero (Maplestory)'],
    ['hoyoung', 'Hoyoung (Maplestory)'],
    ['ice_lightning', 'Archmage of Ice/Lightning (Maplestory)'],
    ['kanna', 'Kanna (Maplestory)'],
    ['kanna_prime', 'Kanna [Prime Form] (Maplestory [Joke-ish])'],
    ['khali', 'Khali (Maplestory)'],
    ['marksman', 'Marksman (Maplestory)'],
    ['mercedes', 'Mercedes (Maplestory)'],
    ['mihile', 'Mihile (Maplestory)'],
    ['night_lord', 'Night Lord (Maplestory)'],
    ['wild_hunter', 'Wild Hunter (Maplestory)'],
    ['zero', 'Zero (Maplestory)'],
    ['ampharos', 'Emma\'s Ampharos (Pokemon)'],
    ['meowstic', 'Olympia\'s Meowstic (Pokemon)'],
    ['serperior', 'Rosa\'s Serperior (Pokemon)']
])