name: Deploy to GitHub Pages

on:
 push:
    branches:
      - master

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}

      - name: Replace placeholder with secret
        run: |
          sed -i 's/API_KEY_PLACEHOLDER/${{ vars.API_GITHUB }}/g' site/src/env/env.prod.ts

      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 24

      - name: npm dependencies
        run: cd site; npm install; npm install -g @angular/cli; git config user.email "rocktalonttaylor@gmail.com"; git config user.name "Serp"

      - name: Deploy to GitHub Pages
        run: |
          cd site; ng deploy --base-href="https://Mach131.github.io/serpexceed/"

permissions:
  contents: write