name: Deploy to GitHub Pages

on:
 push:
    branches:
      - master

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace placeholder with secret
        run: |
          sed -i 's/API_KEY_PLACEHOLDER/${{ vars.API_GITHUB }}/g' site/src/env/env.prod.ts

      - name: Deploy to GitHub Pages
      #   run: |
      #     cd site; ng deploy --base-href="https://Mach131.github.io/serpexceed/"
      # - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.4.0
        with:
          angular_project_dir: site/
          base_href: /serpexceed/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
          deploy_branch: gh-pages # The branch the action should deploy to.
          angular_dist_build_folder: site/dist/test_docs # The folder where your project is supposed to be after running ng build by the action.
